const config = {
  nftStorageApiKey:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDYzMjM5MTUzYjNGYWY5OGYwZTYzMmM3OTUzMDU1NTY1ZDM3Mzc1NDUiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY4MDcyMzgzNzA3OSwibmFtZSI6InRydWV0b2tlbiJ9.R-qCK9Br3BMpyjVZ72vmr-9PoKxj5eMV5eK3-INtRcU",
};

export default config;
